### PR TITLE
Match against correct name of dynamic attributes when using regexes

### LINKED ISSUE #409: Attribute regex breaks prettier linting
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.7.0

**What version of Tailwind CSS are you using?**

v3.4.17

**What version of Node.js are you using?**

v22.20.0

**What package manager are you using?**

NPM

**What operating system are you using?**

Windows

**Reproduction URL**

[Minimal reproduction](https://stackblitz.com/edit/github-xcxobna5?file=app%2Fapp.vue)

**Describe your issue**

I was happy to see the new regex feature and immediately wanted to try it out. Unfortunately, after adding a regex option to the `.prettierrc.json` my code gets partially removed when the regex matches. Stackblitz is also behaving weird now but in VS Code the "custom-class" is matching the regex and the code gets merged/cut that should only be sorted. Is my regex incorrect?

Thanks in advance!

### PR DESCRIPTION
**Pull request by thecrypticace**
Fixes #409

A regex like `/.*-class/` was matching `:custom-class` in Vue files but considered it a static attribute. This is incorrect.

The current implementation was based on a previous version where it built up attribute lists for fast Set-based matching. But really the rules for the parser should just be encoded directly as Vue and Angular have fairly specific rules about which attributes are dynamic vs. static.

This tweaks things to encode those rules directly and fixes the above as a result.

### CODE REVIEW

File: src/options.ts [hunk 1]
```diff
@@ -125,12 +115,47 @@ export function createMatcher(options: RequiredOptions, parser: string, defaults
...
+
     hasFunction: (name: string) => hasMatch(name, functions, functionsRegex),
   }
 }
 
+function nameFromDynamicAttr(name: string, parser: string) {
+  if (parser === 'vue') {
+    if (name.startsWith(':')) return name.slice(1)
+    if (name.startsWith('v-bind:')) return name.slice(7)
+    if (name.startsWith('v-')) return name
```
Comment (RobinMalfait) [inline src/options.ts]: Do we want to slice until the `=` or `:`?

Comment (thecrypticace) [reply src/options.ts]: Nope, the parser has already split the name and value and this only matches against the name.

As for the `:` I think that is only useful with v-bind. Can always change this in the future if we need to.
