### PR TITLE
Resolve `tailwindcss` relative to the file being processed

### LINKED ISSUE #340: v4 classes are not sorted in monorepo where tailwindcss is not installed in package with `.prettierrc`
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.6.9

**What version of Tailwind CSS are you using?**

v4.0.0-beta.9

**What version of Node.js are you using?**

v23.1.0

**What package manager are you using?**

pnpm v9.12.3

**What operating system are you using?**

macOS Version 15.1.1 (24B91)

**Reproduction URL**

https://github.com/adjsky/tailwind-prettier-monorepo-bug

1. Open website/index.html.
2. Try to format the file, see `rotate-360` is not sorted.
3. Run `pnpm add -w tailwindcss@4.0.0-beta.9`.
4. Try to format the file, see `rotate-360` is sorted.
5. Remove tailwindcss from the root `package.json`.
6. Apply website `.prettierrc_` by removing underscore.
7. Try to format the file, see `rotate-360` is still sorted.

**Describe your issue**

Plugin does not sort new classes (`rotate-360`, `h-54.5`, ...) in a monorepo setup, where `tailwindcss` in installed in separate packages, but there is only one `.prettierrc` in the monorepo root.

As i see from the code, the plugin tries to import `tailwindcss` package from the base dir (where the prettier config is located): https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/9481dd0c6ac758a5210b5298b0b4771fdce50c51/src/config.ts#L200

but it fails (since there is no `tailwindcss` package in the root) and falls back to the v3 mode.

This can be fixed by recursively resolving `tailwindcss` in each package from the input file path to the `baseDir`, or at least the current behavior could be documented.

I can open PR with the fixes, if you are welcome.

### LINKED ISSUE #361: I can place a `tailwind.config.js` inside `tailwindStylesheet`
**What version of `prettier-plugin-tailwindcss` are you using?**

0.6.11

**What version of Tailwind CSS are you using?**

4.1.5

**What version of Node.js are you using?**

v20.17.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Reproduction URL**

.

**Describe your issue**

Just noticed that my `tailwindStylesheet` pointed to a  `tailwind.config.js` file instead of the stylesheet.
There is no error, so I thought everything worked fine, but it didn't.
Maybe there should be some sort of validation to make sure `tailwindStylesheet` is a CSS file, and that `tailwindConfig` is a JavaScript file.

### LINKED ISSUE #363: Warn if the path to `tailwindConfig` or `tailwindStylesheet` is invalid
**What version of `prettier-plugin-tailwindcss` are you using?**

0.6.11

**What version of Tailwind CSS are you using?**

4.1.5

**What version of Node.js are you using?**

v20.17.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/main/README.md

**Describe your issue**

Just lost quite a bit of time trying to figure out why my sorting wasn't correct.
Turn out the path inside `tailwindConfig` or `tailwindStylesheet` wasn't correct.
The README says the path is relative to `.prettierrc`, but if you don't put a valid path, the plugin will work poperly but show different errors when running `npm run lint`

package.jon
```
"lint": "eslint --ext .js,.vue ./resources/js"
```

eslint.config.js
```
import pluginVue from 'eslint-plugin-vue';
import globals from 'globals';
import eslintConfigPrettier from 'eslint-config-prettier';
import prettierPlugin from 'eslint-plugin-prettier';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';

export default [
    ...pluginVue.configs['flat/recommended'],
    {
        plugins: {
            prettier: prettierPlugin,
        },
        rules: {
            ...prettierPlugin.configs.recommended.rules,
            ...eslintConfigPrettier.rules,
            ...eslintPluginPrettierRecommended.rules,
            'no-console': 'warn',
            'vue/no-v-html': 'off',
            'vue/multi-word-component-names': 'off',
            'nuxt/no-cjs-in-config': 'off',
            'vue/html-button-has-type': 'error',
            'object-shorthand': ['error', 'always'],
            'no-unused-vars': 'warn',
            'vue/no-unused-components': 'warn',
            'vue/padding-line-between-blocks': ['error', 'always'],
            'vue/no-multiple-template-root': 'off',
            'vue/prop-name-casing': 'off',
            'no-irregular-whitespace': 'off',
            'vue/one-component-per-file': 'off',
            'vue/define-macros-order': [
                'error',
                {
                    order: ['defineOptions', 'defineModel', 'defineProps', 'defineEmits', 'defineSlots'],
                    defineExposeLast: true,
                },
            ],
        },
        languageOptions: {
            sourceType: 'module',
            globals: {
                ...globals.browser,
                ...globals.node,
                axios: true,
                route: true,
                globalThis: true,
                CookieConsent: true,
            },
        },
    },
];
```
.prettierrc:
```json
{
    "printWidth": 120,
    "tabWidth": 4,
    "semi": true,
    "singleQuote": true,
    "trailingComma": "all",
    "plugins": ["prettier-plugin-tailwindcss"],
    "tailwindStylesheet": "./resources/css/app.css"
}
```

### PR DESCRIPTION
**Pull request by thecrypticace**
# Breaking change

## `tailwindcss` is now resolved relative to each processed file

Loading the `tailwindcss` version relative to each processed file produces more correct behavior for monorepos where `tailwindcss` may not be installed at the project root but instead in a subdirectory. Because of this projects with multiple Tailwind CSS versions in the same repo are also more likely to work than before.

## Automatically loaded v3 configs are resolved relative to each processed file

Similar to the above, the same happens when we automatically locate your v3-style config files. Previously these were always searched for relative to the Prettier config — this often meant the file needed to be in the project root. This is no longer the case which should improve support for monorepos with multiple configs using Tailwind CSS v3.

---

This ended up turning into a complete rework of the module and config loading. There's definitely going to be some different perf characteristics because some things are loaded relative to an input file now *but* it's hopefully minimal.

Will need to do lots of perf testing on a large codebase — esp with lots of embedded languages/expressions (e.g. large Vue files).

- [x] Needs implementation tests
- [x] Needs manual performance testing

Closes #243 (since the implementation is now *entirely* different but does the same thing)
Fixes #340
Closes #361
Closes #363
Closes #369

### CODE REVIEW

File: src/versions/v4.ts [hunk 1]
```diff
@@ -0,0 +1,207 @@
+// @ts-check
+import * as fs from 'fs/promises'
+import * as path from 'path'
+import { pathToFileURL } from 'url'
+import { createJiti, type Jiti } from 'jiti'
+import postcss from 'postcss'
+// @ts-ignore
+import postcssImport from 'postcss-import'
```
Comment (RobinMalfait) [inline src/versions/v4.ts:8]: These are unused so can be removed.


```suggestion
```

File: src/versions/v3.ts [hunk 2]
```diff
@@ -0,0 +1,103 @@
+// @ts-check
+import * as path from 'path'
```
Comment (RobinMalfait) [inline src/versions/v3.ts:2]: Not necessary, but just noticed it:
```suggestion
import * as path from 'node:path'
```

File: src/versions/v4.ts [hunk 3]
```diff
@@ -0,0 +1,207 @@
+// @ts-check
+import * as fs from 'fs/promises'
+import * as path from 'path'
+import { pathToFileURL } from 'url'
```
Comment (RobinMalfait) [inline src/versions/v4.ts:4]:
```suggestion
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { pathToFileURL } from 'node:url'
```

File: src/config.ts [hunk 4]
```diff
@@ -1,374 +1,234 @@
 // @ts-check
-import * as fs from 'fs/promises'
 import * as path from 'path'
 import { pathToFileURL } from 'url'
```
Comment (RobinMalfait) [inline src/config.ts:3]:
```suggestion
import * as path from 'node:path'
import { pathToFileURL } from 'node:url'
```

**Review by RobinMalfait — COMMENTED** [review]
Looking good, a few small questions/suggestions.

The `src/config.ts` file reads very nicely right now.

I think technically this change could be a breaking change, but for people with simple setups looking for tailwindcss from the config or input file shouldn't result in any differences. But for people with a more complex (monorepo) setup it should solve locating `tailwindcss` correctly.

Running into some issues with this PR, let's discuss this on Tuple later 👍

**Review by RobinMalfait — APPROVED** [review]
